# Generated by Django 6.0.4 on 2026-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('team_leader', 'Team Leader'), ('admin', 'Admin')], default='member', max_length=20, null=True),
        ),
    ]
