# Generated by Django 6.0.4 on 2026-05-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Member', 'Member'), ('Team Leader', 'Team Leader'), ('Admin', 'Admin')], default='Member', max_length=20, null=True),
        ),
    ]
