# Generated by Django 6.0.4 on 2026-05-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_phone_customuser_contactno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
