# Generated by Django 6.0.2 on 2026-05-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='teams.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='teams.team')),
            ],
            options={
                'unique_together': {('from_team', 'to_team', 'dependency_type')},
            },
        ),
    ]
