# Generated by Django 6.0.2 on 2026-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_update_message_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
