# Generated by Django 6.0.4 on 2026-04-10 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specialization', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('departmentLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
